---
ACTION_ACTIONLINT_ARGUMENTS:
  - -shellcheck=
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TERRAFORM_TERRASCAN
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
