---
fail_fast: true
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: v1.5.1
    hooks:
      - id: opa-fmt
        args: [policies, -w]
      - id: opa-check
        args: [policies, -b]
  - repo: https://github.com/oxsecurity/megalinter
    rev: v7.4.0
    hooks:
      - id: megalinter-incremental
        stages:
          - commit
      - id: megalinter-full
        stages:
          - push
