---
name: "Application Authorization"

concurrency:
  group: ${{ github.workflow }}

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - "application/**.tf"
  workflow_dispatch:
    inputs:
      application:
        description: Authorize an Application
        type: string
        default: ""
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.application }}
    outputs:
      action: ${{ steps.terraform.outputs.action }}
    steps:
      - id: terraform
        name: "Application deployed is: ${{ vars.APPLICATION_DEPLOYED }}"
        shell: bash
        run: |
          env
          if [[ ! -z "${{ vars.APPLICATION_DEPLOYED }}" ]]
          then
            if [[ "${{ vars.APPLICATION_DEPLOYED }}" == "true" ]]
            then
              echo 'action=apply' >> ${GITHUB_OUTPUT}
            else
              echo 'action=destroy' >> ${GITHUB_OUTPUT}
            fi
          else
            echo 'action=skip' >> ${GITHUB_OUTPUT}
          fi

  terraform-plan:
    name: "Terraform Plan"
    needs: [terraform]
    environment: ${{ github.event.inputs.application }}
    if: needs.terraform.outputs.action == 'apply'
    runs-on: ubuntu-latest
    env:
      # this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: "application"

      - name: Applications Initialization
        run: |
          mv application/*.tf ./
          echo 'environments = [' > terraform.auto.tfvars ;
          i=0
          application_branches=($(git ls-remote --heads https://github.com/${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}.git | cut -f 3 -d "/" | grep -v "^main$" | grep -v '-patch-' || true ))
          for branch in "${application_branches[@]}"
          do
            i=$((i+1))
            echo '  {' >> terraform.auto.tfvars
            echo "    REPOSITORY_BRANCH    = \"${branch}\"," >> terraform.auto.tfvars
            echo "    REPOSITORY_FULL_NAME = \"${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}\"," >> terraform.auto.tfvars
            echo "    ARM_SUBSCRIPTION_ID  = \"${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}\"" >> terraform.auto.tfvars
            echo "    ARM_TENANT_ID        = \"${{ secrets.CONTROLLER_ARM_TENANT_ID }}\"" >> terraform.auto.tfvars
            echo "    DEPLOYED             = \"true\"" >> terraform.auto.tfvars
            echo "    AZURE_REGION         = \"${{ secrets.APPLICATION_AZURE_REGION }}\"" >> terraform.auto.tfvars
            echo "    OWNER_EMAIL          = \"${{ secrets.APPLICATION_OWNER_EMAIL }}\"" >> terraform.auto.tfvars
            echo "    CONTROLLER_REPOSITORY_FULL_NAME  = \"${{ github.repository }}\"" >> terraform.auto.tfvars
            echo "    CONTROLLER_REPOSITORY_TOKEN      = \"${{ secrets.CONTROLLER_REPOSITORY_TOKEN }}\"" >> terraform.auto.tfvars
            if [[ "${i}" != "${#application_branches[@]}" ]];then
              echo '  },' >> terraform.auto.tfvars
            else
              echo '  }' >> terraform.auto.tfvars
            fi
          done
          echo ']' >> terraform.auto.tfvars

      - name: Microsoft Azure Authentication
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Hashicorp Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@9501844990f7dcfd09b17a8d97c794d294620f37
        with:
          version: latest

      - name: terraform init
        id: init
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_CLI_ARGS_init: -backend-config="storage_account_name=${{ secrets.CONTROLLER_TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.CONTROLLER_TFSTATE_CONTAINER_NAME }}" -backend-config="resource_group_name=${{ secrets.CONTROLLER_AZURE_RESOURCE_GROUP_NAME }}" -backend-config="key=${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}" -backend-config="use_oidc=true" -input=false
        run: terraform init

      - name: terraform plan
        id: tf-plan
        env:
          GITHUB_TOKEN: ${{ secrets.APPLICATION_REPOSITORY_TOKEN }}
          TF_VAR_repository_full_name: ${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}
          TF_VAR_azure_region: ${{ secrets.APPLICATION_AZURE_REGION }}
          TF_VAR_owner_email: ${{ secrets.APPLICATION_OWNER_EMAIL }}
          TF_VAR_arm_tenant_id: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          TF_VAR_arm_subscription_id: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          TF_VAR_controller_repository_full_name: ${{ github.repository }}
          TF_VAR_controller_repository_token: ${{ secrets.CONTROLLER_REPOSITORY_TOKEN }}
          TF_VAR_deployment_provisioner_role_name: ${{ secrets.DEPLOYMENT_PROVISIONER_ROLE_NAME }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            terraform show -json tfplan | grep '^{.*}$' > tfplan.json
            opa exec --decision terraform/functions/deny --bundle policy/ tfplan.json
            ls -al
            exit 0
          fi

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Render Plan
        id: tf-plan-string
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  terraform-apply:
    name: "Terraform Apply"
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
    environment: ${{ github.event.inputs.application }}
    runs-on: ubuntu-latest
    needs: [terraform-plan]

    steps:
      - name: Github Repository Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: "application"

      - name: Applications Initialization
        run: |
          mv application/*.tf ./
          echo 'environments = [' > terraform.auto.tfvars ;
          i=0
          application_branches=($(git ls-remote --heads https://github.com/${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}.git | cut -f 3 -d "/" | grep -v "^main$" || true ))
          for branch in "${application_branches[@]}"
          do
            i=$((i+1))
            echo '  {' >> terraform.auto.tfvars
            echo "    REPOSITORY_BRANCH    = \"${branch}\"," >> terraform.auto.tfvars
            echo "    REPOSITORY_FULL_NAME = \"${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}\"," >> terraform.auto.tfvars
            echo "    ARM_SUBSCRIPTION_ID  = \"${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}\"" >> terraform.auto.tfvars
            echo "    ARM_TENANT_ID        = \"${{ secrets.CONTROLLER_ARM_TENANT_ID }}\"" >> terraform.auto.tfvars
            echo "    DEPLOYED             = \"false\"" >> terraform.auto.tfvars
            echo "    AZURE_REGION         = \"${{ secrets.APPLICATION_AZURE_REGION }}\"" >> terraform.auto.tfvars
            echo "    OWNER_EMAIL          = \"${{ secrets.APPLICATION_OWNER_EMAIL }}\"" >> terraform.auto.tfvars
            echo "    CONTROLLER_REPOSITORY_FULL_NAME  = \"${{ github.repository }}\"" >> terraform.auto.tfvars
            echo "    CONTROLLER_REPOSITORY_TOKEN      = \"${{ secrets.CONTROLLER_REPOSITORY_TOKEN }}\"" >> terraform.auto.tfvars
            if [[ "${i}" != "${#application_branches[@]}" ]];then
              echo '  },' >> terraform.auto.tfvars
            else
              echo '  }' >> terraform.auto.tfvars
            fi
          done
          echo ']' >> terraform.auto.tfvars

      - name: Microsoft Azure Authentication
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Hashicorp Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: terraform init
        id: init
        env:
          RESOURCE_GROUP_NAME: ${{ secrets.CONTROLLER_AZURE_RESOURCE_GROUP_NAME }}
          TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.CONTROLLER_TFSTATE_STORAGE_ACCOUNT_NAME }}
          TFSTATE_CONTAINER_NAME: ${{ secrets.CONTROLLER_TFSTATE_CONTAINER_NAME }}
          TFSTATE_KEY: ${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_CLI_ARGS_init: -backend-config="storage_account_name=${{ secrets.CONTROLLER_TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.CONTROLLER_TFSTATE_CONTAINER_NAME }}" -backend-config="resource_group_name=${{ secrets.CONTROLLER_AZURE_RESOURCE_GROUP_NAME }}" -backend-config="key=${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}" -backend-config="use_oidc=true" -input=false
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: terraform apply
        env:
          GITHUB_TOKEN: ${{ secrets.APPLICATION_REPOSITORY_TOKEN }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform apply -auto-approve tfplan

  destroy:
    name: "Terraform Destroy"
    needs: [terraform]
    if: needs.terraform.outputs.action == 'destroy'
    environment: ${{ github.event.inputs.application }}
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: "application"

      - name: Applications Initialization
        run: |
          mv application/*.tf ./
          echo 'environments = [' > terraform.auto.tfvars ;
          i=0
          application_branches=($(git ls-remote --heads https://github.com/${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}.git | cut -f 3 -d "/" | grep -v "^main$" || true ))
          for branch in "${application_branches[@]}"
          do
            i=$((i+1))
            echo '  {' >> terraform.auto.tfvars
            echo "    REPOSITORY_BRANCH    = \"${branch}\"," >> terraform.auto.tfvars
            echo "    REPOSITORY_FULL_NAME = \"${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}\"," >> terraform.auto.tfvars
            echo "    ARM_SUBSCRIPTION_ID  = \"${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}\"" >> terraform.auto.tfvars
            echo "    ARM_TENANT_ID        = \"${{ secrets.CONTROLLER_ARM_TENANT_ID }}\"" >> terraform.auto.tfvars
            echo "    DEPLOYED             = \"false\"" >> terraform.auto.tfvars
            echo "    AZURE_REGION         = \"${{ secrets.APPLICATION_AZURE_REGION }}\"" >> terraform.auto.tfvars
            echo "    OWNER_EMAIL          = \"${{ secrets.APPLICATION_OWNER_EMAIL }}\"" >> terraform.auto.tfvars
            echo "    CONTROLLER_REPOSITORY_FULL_NAME  = \"${{ github.repository }}\"" >> terraform.auto.tfvars
            echo "    CONTROLLER_REPOSITORY_TOKEN      = \"${{ secrets.CONTROLLER_REPOSITORY_TOKEN }}\"" >> terraform.auto.tfvars
            if [[ "${i}" != "${#application_branches[@]}" ]];then
              echo '  },' >> terraform.auto.tfvars
            else
              echo '  }' >> terraform.auto.tfvars
            fi
          done
          echo ']' >> terraform.auto.tfvars

      - name: Microsoft Azure Authentication
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Hashicorp Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: terraform init
        id: init
        env:
          RESOURCE_GROUP_NAME: ${{ secrets.CONTROLLER_AZURE_RESOURCE_GROUP_NAME }}
          TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.CONTROLLER_TFSTATE_STORAGE_ACCOUNT_NAME }}
          TFSTATE_CONTAINER_NAME: ${{ secrets.CONTROLLER_TFSTATE_CONTAINER_NAME }}
          TFSTATE_KEY: ${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_CLI_ARGS_init: -backend-config="storage_account_name=${{ secrets.CONTROLLER_TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.CONTROLLER_TFSTATE_CONTAINER_NAME }}" -backend-config="resource_group_name=${{ secrets.CONTROLLER_AZURE_RESOURCE_GROUP_NAME }}" -backend-config="key=${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}" -backend-config="use_oidc=true" -input=false
        run: terraform init

      - name: terraform destroy
        id: destroy
        env:
          GITHUB_TOKEN: ${{ secrets.APPLICATION_REPOSITORY_TOKEN }}
          TF_VAR_repository_full_name: ${{ secrets.APPLICATION_REPOSITORY_FULL_NAME }}
          TF_VAR_azure_region: ${{ secrets.APPLICATION_AZURE_REGION }}
          TF_VAR_owner_email: ${{ secrets.APPLICATION_OWNER_EMAIL }}
          TF_VAR_arm_tenant_id: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          TF_VAR_arm_subscription_id: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          TF_VAR_controller_repository_full_name: ${{ github.repository }}
          TF_VAR_controller_repository_token: ${{ secrets.CONTROLLER_REPOSITORY_TOKEN }}
          TF_VAR_deployment_provisioner_role_name: ${{ secrets.DEPLOYMENT_PROVISIONER_ROLE_NAME }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.CONTROLLER_ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.CONTROLLER_ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          terraform destroy -auto-approve
