name: Dispatch Listener

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Load an Environment
        type: string
        default: ''
        required: true

jobs:
  say_hello:
    environment: 
    runs-on: ubuntu-latest
    steps:
      - name: Set merged variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - name: Print workflow_dispatch inputs
        run: echo "${{ toJson(github.event.inputs) }}"

