name: Dispatch Listener

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          ENVIRONMENT='${{ toJSON(github.event.client_payload.environment) }}'
          echo "${ENVIRONMENT}"
